#!/usr/bin/env python3
"""Generate Unicode + entity tables for crates/ast.

Outputs (relative to crates/ast/):
  src/parser/tables.rs   - Unicode punctuation/symbol + Zs ranges, casefold map
  src/parser/entities.rs - HTML5 named entity table (semicolon forms only)

Inputs: entities.json (vendored from https://html.spec.whatwg.org/entities.json).
Unicode data comes from the running Python's unicodedata module; the UCD
version is recorded in the generated header.

Run from this directory: python3 gen_tables.py
Then run `cargo fmt` — output is close to rustfmt style but not guaranteed.
"""

import json
import sys
import unicodedata
from pathlib import Path

SPEC_DIR = Path(__file__).resolve().parent
AST_DIR = SPEC_DIR.parent.parent


def rust_str(s: str) -> str:
    out = []
    for ch in s:
        if ch in ('"', "\\"):
            out.append("\\" + ch)
        elif 0x20 <= ord(ch) < 0x7F:
            out.append(ch)
        else:
            out.append(f"\\u{{{ord(ch):x}}}")
    return '"' + "".join(out) + '"'


def char_ranges(pred):
    ranges = []
    start = None
    for c in range(0x110000):
        if 0xD800 <= c <= 0xDFFF:
            ok = False
        else:
            ok = pred(chr(c))
        if ok and start is None:
            start = c
        elif not ok and start is not None:
            ranges.append((start, c - 1))
            start = None
    if start is not None:
        ranges.append((start, 0x10FFFF))
    return ranges


def emit_ranges(name, doc, ranges):
    lines = [f"/// {doc}", f"pub static {name}: &[(u32, u32)] = &["]
    for a, b in ranges:
        lines.append(f"    ({a:#x}, {b:#x}),")
    lines.append("];\n")
    return "\n".join(lines)


def gen_tables():
    ucd = unicodedata.unidata_version
    header = (
        "//! Generated by `tests/spec/gen_tables.py` — do not edit by hand.\n"
        f"//! Unicode data: Python `unicodedata`, UCD {ucd}.\n"
        "//!\n"
        "//! CommonMark 0.31.2 defines a \"Unicode punctuation character\" as\n"
        "//! anything in the P or S general categories, and \"Unicode\n"
        "//! whitespace\" as Zs plus tab/LF/FF/CR (the ASCII part is handled\n"
        "//! in code, not here).\n\n"
    )
    punct = char_ranges(lambda ch: unicodedata.category(ch)[0] in "PS")
    zs = char_ranges(lambda ch: unicodedata.category(ch) == "Zs")

    folds = []
    for c in range(0x110000):
        if 0xD800 <= c <= 0xDFFF:
            continue
        ch = chr(c)
        f = ch.casefold()
        if f != ch:
            folds.append((c, f))

    body = [header]
    body.append(
        emit_ranges(
            "PUNCT_SYMBOL",
            "Sorted, inclusive codepoint ranges of general categories P* and S*.",
            punct,
        )
    )
    body.append(
        emit_ranges(
            "ZS", "Sorted, inclusive codepoint ranges of general category Zs.", zs
        )
    )
    body.append(
        "/// Full case folding (C+F): sorted by codepoint; chars that fold to\n"
        "/// themselves are omitted. Used for link-label unification.\n"
        "pub static CASEFOLD: &[(u32, &str)] = &["
    )
    for c, f in folds:
        body.append(f"    ({c:#x}, {rust_str(f)}),")
    body.append("];\n")

    out = AST_DIR / "src" / "parser" / "tables.rs"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(body), encoding="utf-8")
    print(f"{out}: {len(punct)} punct ranges, {len(zs)} zs ranges, {len(folds)} folds")


def gen_entities():
    data = json.loads((SPEC_DIR / "entities.json").read_text(encoding="utf-8"))
    entries = []
    for name, info in data.items():
        # CommonMark recognizes only the semicolon-terminated forms.
        if not (name.startswith("&") and name.endswith(";")):
            continue
        entries.append((name[1:-1], info["characters"]))
    entries.sort(key=lambda e: e[0])

    lines = [
        "//! Generated by `tests/spec/gen_tables.py` — do not edit by hand.",
        "//! Source: tests/spec/entities.json (vendored from",
        "//! <https://html.spec.whatwg.org/entities.json>). Semicolon forms only,",
        "//! per the CommonMark 0.31.2 entity rules.",
        "",
        "/// Sorted by name (bytewise) for binary search: (name, replacement).",
        "pub static ENTITIES: &[(&str, &str)] = &[",
    ]
    for name, chars in entries:
        lines.append(f"    ({rust_str(name)}, {rust_str(chars)}),")
    lines.append("];\n")

    out = AST_DIR / "src" / "parser" / "entities.rs"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"{out}: {len(entries)} entities")


if __name__ == "__main__":
    gen_tables()
    gen_entities()
    sys.exit(0)
